#!/usr/bin/env bash
#A bash script that displays a list of currently running processes
#Displays all processes for all users including those without TTY
#In a user oriented format showing process hierachy

ps auxf
