#!/usr/bin/env bash
# A Bash script that creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and
#terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

cleanup() {
    rm -f /var/run/myscript.pid
    # Terminate the script
    exit 0
}

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap cleanup SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 1
done
