#!/usr/bin/env bash
#A script that displays 'Best School' 10 times and hi on 9th iteration

count=0

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
