#!/usr/bin/env bash
#A bash script that loops from 1-10
#Displays bad luck for the 4th loop iteration
#Displays good luck for the 8th loop iteration
#Displays Best School for the other iterations

count=0
while [ $count -le 9 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
