#!/usr/bin/env bash
# This script takes one argument as the username and runs the 'whoami' command under that user.

if [ $# -eq 1 ]; then
  username="$1"
  sudo -u "$username" whoami
else
  echo "Usage: $0 <username>"
fi

